# 配置dev环境

server:
  port: 8084

spring:
  profiles: dev
  # 指定当前微服务对外暴露的名称
  application:
    name: abcmsc-provider-config

  # 配置 spring-data-jpa
  jpa:
    # 应用启动时是否自动建表，默认为false
    generate-ddl: true
    # 是否在控制台显示sql语句，默认为false
    show-sql: true
    # 设置应用启动时不重新建表
    hibernate:
      ddl-auto: none

  # 配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///test02?useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: root


eureka:
  # 指定eureka服务中心
  client:
    service-url: http://eureka8400:8400/eureka

logging:
  # 设置日志输出格式
  pattern:
    console: level-%level %msg %n
  level:
    # Spring Boot启动时的日志级别
    root: info
    # Hibernate运行日志级别
    org.hibernate: info
    # 在show-sql为true时显示SQL中的动态参数值
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    # 在show-sql为true时显示查询结果
    org.hibernate.type.descriptor.sql.BasicExtractor: trace
    # 控制自己代码运行时显示的日志级别
    com.kaikeba.provider: debug

---
# 配置test环境

server:
  port: 8085

spring:
  profiles: test
  # 指定当前微服务对外暴露的名称
  application:
    name: abcmsc-provider-config

  # 配置 spring-data-jpa
  jpa:
    # 应用启动时是否自动建表，默认为false
    generate-ddl: true
    # 是否在控制台显示sql语句，默认为false
    show-sql: true
    # 设置应用启动时不重新建表
    hibernate:
      ddl-auto: none

  # 配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///test03?useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: root


eureka:
  # 指定eureka服务中心
  client:
    service-url: http://eureka8500:8500/eureka

logging:
  # 设置日志输出格式
  pattern:
    console: level-%level %msg %n
  level:
    # Spring Boot启动时的日志级别
    root: info
    # Hibernate运行日志级别
    org.hibernate: info
    # 在show-sql为true时显示SQL中的动态参数值
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    # 在show-sql为true时显示查询结果
    org.hibernate.type.descriptor.sql.BasicExtractor: trace
    # 控制自己代码运行时显示的日志级别
    com.kaikeba.provider: debug
