# 配置dev环境
server:
  port: 8400

spring:
  profiles: dev
  application:
    name: abcmsc-eurekaServer-config

eureka:
  instance:
    hostname: eureka8400.com  # 指定eureka主机
  client:
    register-with-eureka: false # 指定是否向注册中心注册自己
    fetch-registry: false # 指定次客户端是否能获取eureka注册信息
    service-url:  # 暴露服务中心地址
      defaultZone: http://euraka8400.com:8400/eureka

---
# 配置test环境

server:
  port: 8500

spring:
  profiles: test
  application:
    name: abcmsc-eurekaServer-config

eureka:
  instance:
    hostname: eureka8500.com  # 指定eureka主机
  client:
    register-with-eureka: false # 指定是否向注册中心注册自己
    fetch-registry: false # 指定次客户端是否能获取eureka注册信息
    service-url:  # 暴露服务中心地址
      defaultZone: http://euraka8500.com:8500/eureka