# 配置dev环境
server:
  port: 7070

spring:
  profiles: dev
  application: # 指定微服务对外暴露的名称
    name: abcmsc-consumer-depart

eureka:
  client:
    service-url: # 指定eureka服务注册中心
      defaultZone: http://localhost:8400/eureka

# 开启feign对Hystrix的支持
feign:
  hystrix:
    enabled: true

# 设置服务熔断时限，默认为5000毫秒
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

---
# 配置test环境
server:
  port: 9090

spring:
  profiles: test
  application: # 指定微服务对外暴露的名称
    name: abcmsc-consumer-depart

eureka:
  client:
    service-url: # 指定eureka服务注册中心
      defaultZone: http://localhost:8500/eureka

# 开启feign对Hystrix的支持
feign:
  hystrix:
    enabled: true

# 设置服务熔断时限，默认为5000毫秒
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000